// ============================================================
// routes/agreementRoutes.js — Agreement URL Definitions
// ============================================================
//
// ROUTE DESIGN OVERVIEW:
//   All routes are under the /api/agreements prefix (set in server.js).
//   Every route is PRIVATE — JWT verification is required.
//
// IMPORTANT — ROUTE ORDER:
//   The /:id/download route must come BEFORE a generic /:id route
//   to avoid Express treating "download" as an ID parameter.
//
// WHY NO CREATE/UPDATE ROUTES?
//   Agreements are NOT created or updated directly by users.
//   They are auto-generated by the borrow request workflow:
//     - Created when a borrow request is APPROVED
//     - Completed when an item is marked as RETURNED
//   This is intentional — it prevents users from creating fake
//   agreements or modifying them after the fact.
//
// ROUTE MAP:
//   GET  /api/agreements              → List all my agreements
//   GET  /api/agreements/:id          → Get specific agreement
//   GET  /api/agreements/:id/download → Download agreement PDF
// ============================================================

const express = require("express");
const router = express.Router();

// Import controller functions
const {
  getAgreementById,
  getMyAgreements,
  downloadAgreementPDF,
} = require("../controllers/agreementController");

// Import protect middleware (JWT verification)
const { protect } = require("../middleware/authMiddleware");

// ============================================================
// All routes below require authentication (valid JWT)
// ============================================================

// --- List all agreements for the logged-in user ---
// GET /api/agreements
// Returns agreements where user is either borrower or owner
router.get("/", protect, getMyAgreements);

// --- Download the PDF for a specific agreement ---
// GET /api/agreements/:id/download
// ⚠️ Must be ABOVE the generic /:id route
router.get("/:id/download", protect, downloadAgreementPDF);

// --- Get a specific agreement by ID ---
// GET /api/agreements/:id
router.get("/:id", protect, getAgreementById);

module.exports = router;
